%% EXERCISE 2
% Distribution of random numbers (exponential) generated by uniform 
% distribution

lambda = 1;

% generate random numbers using uniform distribution
y = -1/lambda * log(1-rand(1e3,1));

histogram(y,'Normalization','pdf')

%show exponential 0-1
hold on
x = 0:0.01:10;
showExp = pdf('Exponential',x,1/lambda);
plot(x,showExp,'LineWidth',2)

xlabel('$X$','Interpreter','latex')
ylabel('$f_{x}(X)$','Interpreter','latex')
